// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK82et16mHOVl_UamCJDsGvmci9lwoQlI',
    appId: '1:853285394238:web:a2a62daa56741fc7b27e6f',
    messagingSenderId: '853285394238',
    projectId: 'chat-c2c47',
    authDomain: 'chat-c2c47.firebaseapp.com',
    storageBucket: 'chat-c2c47.firebasestorage.app',
    measurementId: 'G-6XLG1V79W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA764OB5_ep92b4yFnV_SFVOCVwe-yu-Ng',
    appId: '1:853285394238:android:7451f3a1c118e024b27e6f',
    messagingSenderId: '853285394238',
    projectId: 'chat-c2c47',
    storageBucket: 'chat-c2c47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWmCo0WodnqNR0pwWPHE_Y2SEBD-SeqOQ',
    appId: '1:853285394238:ios:03def09b60a866c5b27e6f',
    messagingSenderId: '853285394238',
    projectId: 'chat-c2c47',
    storageBucket: 'chat-c2c47.firebasestorage.app',
    iosBundleId: 'com.example.riverpodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWmCo0WodnqNR0pwWPHE_Y2SEBD-SeqOQ',
    appId: '1:853285394238:ios:03def09b60a866c5b27e6f',
    messagingSenderId: '853285394238',
    projectId: 'chat-c2c47',
    storageBucket: 'chat-c2c47.firebasestorage.app',
    iosBundleId: 'com.example.riverpodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK82et16mHOVl_UamCJDsGvmci9lwoQlI',
    appId: '1:853285394238:web:5f96ea25ee464a2ab27e6f',
    messagingSenderId: '853285394238',
    projectId: 'chat-c2c47',
    authDomain: 'chat-c2c47.firebaseapp.com',
    storageBucket: 'chat-c2c47.firebasestorage.app',
    measurementId: 'G-LB65S5SXRD',
  );
}
